// Generated by packages/contracts/tools/generate-csharp.py; regenerate from Zod schemas.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Trail.Contracts
{
    public sealed class AuthoredCapture
    {
        public int SchemaVersion { get; set; }
        public Recording Recording { get; set; }
        public TakeAuthoringMetadata Authoring { get; set; }
    }
    public sealed class Recording
    {
        public int SchemaVersion { get; set; }
        public string Id { get; set; }
        public string CoordinateFrame { get; set; }
        public WorkspaceDefinition Workspace { get; set; }
        public string[] JointOrder { get; set; }
        public int NominalSampleHz { get; set; }
        public double DurationMs { get; set; }
        public MotionFrame[] Frames { get; set; }
        public StepMarker[] Markers { get; set; }
        public AudioAsset Audio { get; set; }
        public string Source { get; set; }
    }
    public sealed class WorkspaceDefinition
    {
        public string Id { get; set; }
        public int Version { get; set; }
        public double WidthM { get; set; }
        public double DepthM { get; set; }
        public CalibrationMarks CalibrationMarksM { get; set; }
        public string LayoutId { get; set; }
        public string DominantHand { get; set; }
        public string CalibrationMethod { get; set; }
    }
    public sealed class CalibrationMarks
    {
        public Vector3 A { get; set; }
        public Vector3 B { get; set; }
        public Vector3 C { get; set; }
        public Vector3 D { get; set; }
    }
    public sealed class MotionFrame
    {
        public double TMs { get; set; }
        public HandSamples Hands { get; set; }
        public CanonicalPose? Head { get; set; }
    }
    public sealed class HandSamples
    {
        public HandSample Left { get; set; }
        public HandSample Right { get; set; }
    }
    public sealed class HandSample
    {
        public string Status { get; set; }
        public string Reason { get; set; }
        public Dictionary<string, CanonicalPose> Joints { get; set; }
    }
    public sealed class StepMarker
    {
        public string Id { get; set; }
        public double TMs { get; set; }
        public string Kind { get; set; }
        public string Source { get; set; }
    }
    public sealed class AudioAsset
    {
        public string AssetId { get; set; }
        public string MimeType { get; set; }
        public double DurationMs { get; set; }
        public double AudioStartOffsetMs { get; set; }
        public string SyncMethod { get; set; }
        public double? EstimatedSyncErrorMs { get; set; }
    }
    public sealed class TakeAuthoringMetadata
    {
        public int SchemaVersion { get; set; }
        public string TutorialId { get; set; }
        public int TakeIndex { get; set; }
        public TakeAuthoringMetadataSavePosition SavePosition { get; set; }
        public TakeAuthoringMetadataTrim Trim { get; set; }
        public string TrimReason { get; set; }
    }
    public sealed class TakeAuthoringMetadataSavePosition
    {
        public Vector3 LeftM { get; set; }
        public Vector3 RightM { get; set; }
    }
    public sealed class TakeAuthoringMetadataTrim
    {
        public double StartMs { get; set; }
        public double EndMsExclusive { get; set; }
    }
    public sealed class CalibrationV2
    {
        public int SchemaVersion { get; set; }
        public string Id { get; set; }
        public string ReferenceSpaceType { get; set; }
        public string TrackingSessionId { get; set; }
        public int OriginRevision { get; set; }
        public CanonicalPose ReferenceFromWorkspace { get; set; }
        public Vector3[] SampledReferencePointsM { get; set; }
        public double VerificationErrorM { get; set; }
        public bool Valid { get; set; }
    }
    public sealed class ClockMapping
    {
        public string Source { get; set; }
        public double OffsetToMonotonicMs { get; set; }
        public double UncertaintyMs { get; set; }
    }
    public sealed class CoachAssessment
    {
        public string Verdict { get; set; }
        public string[] ObservedEvidence { get; set; }
        public string Limitation { get; set; }
        public string Feedback { get; set; }
        public string SuggestedAction { get; set; }
    }
    public sealed class CreateRecordingRequest
    {
        public RecordingMetadata Metadata { get; set; }
    }
    public sealed class RecordingMetadata
    {
        public int SchemaVersion { get; set; }
        public string Id { get; set; }
        public string CoordinateFrame { get; set; }
        public WorkspaceDefinition Workspace { get; set; }
        public string[] JointOrder { get; set; }
        public int NominalSampleHz { get; set; }
        public double DurationMs { get; set; }
        public StepMarker[] Markers { get; set; }
        public AudioAsset Audio { get; set; }
        public string Source { get; set; }
    }
    public sealed class FinalizeRecordingRequest
    {
        public int ChunkCount { get; set; }
        public string Sha256 { get; set; }
    }
    public sealed class GuideContextRef
    {
        public string RunId { get; set; }
        public string TutorialId { get; set; }
        public int TutorialRevision { get; set; }
        public string StepId { get; set; }
        public int StepRevision { get; set; }
        public string AttemptId { get; set; }
    }
    public sealed class GuideEvent
    {
        public int SchemaVersion { get; set; }
        public string SessionId { get; set; }
        public string RunId { get; set; }
        public long Seq { get; set; }
        public double TMs { get; set; }
        public string Type { get; set; }
        public GuideSnapshot State { get; set; }
        public string StepId { get; set; }
        public string AttemptId { get; set; }
        public string Evidence { get; set; }
        public string Reason { get; set; }
    }
    public sealed class GuideSnapshot
    {
        public string Phase { get; set; }
        public string TutorialId { get; set; }
        public int TutorialRevision { get; set; }
        public string StepId { get; set; }
        public int StepRevision { get; set; }
        public string AttemptId { get; set; }
        public double DwellProgress { get; set; }
        public double PathProgress { get; set; }
        public NextGateByHand NextGateByHand { get; set; }
        public bool CalibrationValid { get; set; }
        public HandTracking Tracking { get; set; }
    }
    public sealed class NextGateByHand
    {
        public int? Left { get; set; }
        public int? Right { get; set; }
    }
    public sealed class HandTracking
    {
        public string Left { get; set; }
        public string Right { get; set; }
    }
    public sealed class HandTarget
    {
        public string Side { get; set; }
        public string Joint { get; set; }
        public CanonicalPose StartPose { get; set; }
        public CanonicalPose CheckpointPose { get; set; }
        public double PositionToleranceM { get; set; }
        public double? OrientationToleranceRad { get; set; }
        public string Gesture { get; set; }
        public MotionGate[] MotionGates { get; set; }
        public double PathCorridorM { get; set; }
    }
    public sealed class MotionGate
    {
        public int FrameIndex { get; set; }
        public Vector3 PositionM { get; set; }
        public double ToleranceM { get; set; }
        public double DwellMs { get; set; }
    }
    public sealed class InspectionRequest
    {
        public string RunId { get; set; }
        public string TutorialId { get; set; }
        public int TutorialRevision { get; set; }
        public string StepId { get; set; }
        public int StepRevision { get; set; }
        public string AttemptId { get; set; }
        public string RequestId { get; set; }
        public string LiveSessionId { get; set; }
        public int SessionGeneration { get; set; }
        public int RequestEpoch { get; set; }
        public string DelegationId { get; set; }
        public string Question { get; set; }
        public string[] ReferenceIds { get; set; }
    }
    public sealed class InspectionResult
    {
        public InspectionRequest Request { get; set; }
        public string ObservationId { get; set; }
        public string[] ReferenceIds { get; set; }
        public CoachAssessment Assessment { get; set; }
        public string Provenance { get; set; }
    }
    public sealed class MotionChunk
    {
        public MotionFrame[] Frames { get; set; }
        public string Sha256 { get; set; }
    }
    public sealed class NativeCaptureSidecar
    {
        public int SchemaVersion { get; set; }
        public string RecordingId { get; set; }
        public string RecordingHash { get; set; }
        public string TrackingSessionId { get; set; }
        public int OriginRevision { get; set; }
        public string Provider { get; set; }
        public string EditorVersion { get; set; }
        public string SdkVersion { get; set; }
        public string Skeleton { get; set; }
        public string AdapterVersion { get; set; }
        public ClockMapping Clock { get; set; }
        public string ConfidencePolicy { get; set; }
        public string Source { get; set; }
    }
    public sealed class RecordingByteChunk
    {
        public string DataBase64 { get; set; }
        public string Sha256 { get; set; }
    }
    public sealed class ReferenceEdit
    {
        public int BaseRevision { get; set; }
        public StepSceneReference[] References { get; set; }
    }
    public sealed class StepSceneReference
    {
        public string Id { get; set; }
        public string RecordingId { get; set; }
        public string RecordingHash { get; set; }
        public string TutorialId { get; set; }
        public int TutorialRevision { get; set; }
        public string StepId { get; set; }
        public string AssetId { get; set; }
        public string Source { get; set; }
        public string VisibleOutcome { get; set; }
    }
    public sealed class ReferenceImageUpload
    {
        public string RecordingId { get; set; }
        public string RecordingHash { get; set; }
        public int FrameIndex { get; set; }
        public string Source { get; set; }
        public ReferenceImageUploadImage Image { get; set; }
    }
    public sealed class ReferenceImageUploadImage
    {
        public string MimeType { get; set; }
        public string DataBase64 { get; set; }
        public string Sha256 { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    }
    public sealed class SceneObservation
    {
        public string Id { get; set; }
        public string RequestId { get; set; }
        public string CaptureNonce { get; set; }
        public string SourceSessionId { get; set; }
        public string Source { get; set; }
        public string AssetId { get; set; }
        public long SourceFrameSeq { get; set; }
        public double CaptureAgeAtSendMs { get; set; }
        public double ReceivedAtServerMonoMs { get; set; }
    }
    public sealed class SceneReferenceManifest
    {
        public int SchemaVersion { get; set; }
        public string RecordingId { get; set; }
        public string RecordingHash { get; set; }
        public string TutorialId { get; set; }
        public int TutorialRevision { get; set; }
        public StepSceneReference[] References { get; set; }
    }
    public sealed class SpectatorState
    {
        public string Type { get; set; }
        public bool Connected { get; set; }
        public double UpdatedAt { get; set; }
        public double AgeMs { get; set; }
        public GuideEvent Snapshot { get; set; }
        public SpectatorStateStep Step { get; set; }
    }
    public sealed class SpectatorStateStep
    {
        public string Title { get; set; }
        public string Instruction { get; set; }
        public long Index { get; set; }
        public long Total { get; set; }
        public string CompletionMode { get; set; }
        public string Source { get; set; }
    }
    public sealed class Tutorial
    {
        public int SchemaVersion { get; set; }
        public string Id { get; set; }
        public int Revision { get; set; }
        public string RecordingId { get; set; }
        public string RecordingHash { get; set; }
        public WorkspaceDefinition Workspace { get; set; }
        public string Status { get; set; }
        public TutorialStep[] Steps { get; set; }
        public TutorialProvenance Provenance { get; set; }
    }
    public sealed class TutorialStep
    {
        public string Id { get; set; }
        public int StartFrame { get; set; }
        public int EndFrameExclusive { get; set; }
        public int CheckpointFrame { get; set; }
        public string Title { get; set; }
        public string Instruction { get; set; }
        public HandTarget[] Targets { get; set; }
        public double DwellMs { get; set; }
        public double StartDwellMs { get; set; }
        public string CompletionMode { get; set; }
        public string[] NarrationSpanIds { get; set; }
    }
    public sealed class TutorialProvenance
    {
        public string Segmentation { get; set; }
        public string Labels { get; set; }
        public string Model { get; set; }
        public string PromptVersion { get; set; }
    }
    public sealed class TutorialDraftEdit
    {
        public int BaseRevision { get; set; }
        public TutorialDraftStep[] Steps { get; set; }
    }
    public sealed class TutorialDraftStep
    {
        public string Id { get; set; }
        public int StartFrame { get; set; }
        public int EndFrameExclusive { get; set; }
        public int CheckpointFrame { get; set; }
        public string[] ActiveHands { get; set; }
        public string CompletionMode { get; set; }
        public string Title { get; set; }
        public string Instruction { get; set; }
    }
    public sealed class TutorialFinalize
    {
        public int BaseRevision { get; set; }
    }
    public sealed class TutorialJobCreate
    {
        public string RecordingId { get; set; }
        public string RecordingHash { get; set; }
        public int SegmentationRevision { get; set; }
    }
    public sealed class TutorialLabelBatch
    {
        public int BaseRevision { get; set; }
        public string RecordingHash { get; set; }
        public TutorialLabelBatchLabelsItem[] Labels { get; set; }
        public TutorialLabelBatchProvenance Provenance { get; set; }
    }
    public sealed class TutorialLabelBatchLabelsItem
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Instruction { get; set; }
        public string[] NarrationSpanIds { get; set; }
    }
    public sealed class TutorialLabelBatchProvenance
    {
        public string Labels { get; set; }
        public string Model { get; set; }
        public string PromptVersion { get; set; }
    }
}
