// Generated by packages/contracts/tools/generate-csharp.py; regenerate from Zod schemas.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace Trail.Contracts
{
    public static partial class ContractJson
    {
        public static CalibrationV2 ParseCalibrationV2(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("CalibrationV2", raw); return ReadCalibrationV2(raw); }
        public static string SerializeCalibrationV2(CalibrationV2 value) { var json = StrictJson.Stringify(WriteCalibrationV2(value)); ParseCalibrationV2(json); return json; }
        private static CalibrationV2 ReadCalibrationV2(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new CalibrationV2();
            if (map.ContainsKey("schemaVersion")) result.SchemaVersion = (int)(double)map["schemaVersion"];
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("referenceSpaceType")) result.ReferenceSpaceType = (string)map["referenceSpaceType"];
            if (map.ContainsKey("trackingSessionId")) result.TrackingSessionId = (string)map["trackingSessionId"];
            if (map.ContainsKey("originRevision")) result.OriginRevision = (int)(double)map["originRevision"];
            if (map.ContainsKey("referenceFromWorkspace")) result.ReferenceFromWorkspace = ReadPose(map["referenceFromWorkspace"]);
            if (map.ContainsKey("sampledReferencePointsM")) result.SampledReferencePointsM = ((List<object>)map["sampledReferencePointsM"]).Select(item => ReadVec3(item)).ToArray();
            if (map.ContainsKey("verificationErrorM")) result.VerificationErrorM = (double)(double)map["verificationErrorM"];
            if (map.ContainsKey("valid")) result.Valid = (bool)map["valid"];
            return result;
        }
        private static object WriteCalibrationV2(CalibrationV2 value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["id"] = (object)value.Id;
            map["referenceSpaceType"] = (object)value.ReferenceSpaceType;
            map["trackingSessionId"] = (object)value.TrackingSessionId;
            map["originRevision"] = (object)value.OriginRevision;
            map["referenceFromWorkspace"] = WritePose(value.ReferenceFromWorkspace);
            map["sampledReferencePointsM"] = (value.SampledReferencePointsM == null ? null : value.SampledReferencePointsM.Select(item => WriteVec3(item)).ToList());
            map["verificationErrorM"] = (object)value.VerificationErrorM;
            map["valid"] = (object)value.Valid;
            return map;
        }
        public static ClockMapping ParseClockMapping(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("ClockMapping", raw); return ReadClockMapping(raw); }
        public static string SerializeClockMapping(ClockMapping value) { var json = StrictJson.Stringify(WriteClockMapping(value)); ParseClockMapping(json); return json; }
        private static ClockMapping ReadClockMapping(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new ClockMapping();
            if (map.ContainsKey("source")) result.Source = (string)map["source"];
            if (map.ContainsKey("offsetToMonotonicMs")) result.OffsetToMonotonicMs = (double)(double)map["offsetToMonotonicMs"];
            if (map.ContainsKey("uncertaintyMs")) result.UncertaintyMs = (double)(double)map["uncertaintyMs"];
            return result;
        }
        private static object WriteClockMapping(ClockMapping value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["source"] = (object)value.Source;
            map["offsetToMonotonicMs"] = (object)value.OffsetToMonotonicMs;
            map["uncertaintyMs"] = (object)value.UncertaintyMs;
            return map;
        }
        public static CoachAssessment ParseCoachAssessment(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("CoachAssessment", raw); return ReadCoachAssessment(raw); }
        public static string SerializeCoachAssessment(CoachAssessment value) { var json = StrictJson.Stringify(WriteCoachAssessment(value)); ParseCoachAssessment(json); return json; }
        private static CoachAssessment ReadCoachAssessment(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new CoachAssessment();
            if (map.ContainsKey("verdict")) result.Verdict = (string)map["verdict"];
            if (map.ContainsKey("observedEvidence")) result.ObservedEvidence = ((List<object>)map["observedEvidence"]).Select(item => (string)item).ToArray();
            if (map.ContainsKey("limitation")) result.Limitation = (string)map["limitation"];
            if (map.ContainsKey("feedback")) result.Feedback = (string)map["feedback"];
            if (map.ContainsKey("suggestedAction")) result.SuggestedAction = (string)map["suggestedAction"];
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteCoachAssessment(CoachAssessment value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["verdict"] = (object)value.Verdict;
            map["observedEvidence"] = (value.ObservedEvidence == null ? null : value.ObservedEvidence.Select(item => (object)item).ToList());
            map["limitation"] = (object)value.Limitation;
            map["feedback"] = (object)value.Feedback;
            map["suggestedAction"] = (object)value.SuggestedAction;
            return map;
        }
        public static CreateRecordingRequest ParseCreateRecordingRequest(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("CreateRecordingRequest", raw); return ReadCreateRecordingRequest(raw); }
        public static string SerializeCreateRecordingRequest(CreateRecordingRequest value) { var json = StrictJson.Stringify(WriteCreateRecordingRequest(value)); ParseCreateRecordingRequest(json); return json; }
        private static CreateRecordingRequest ReadCreateRecordingRequest(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new CreateRecordingRequest();
            if (map.ContainsKey("metadata")) result.Metadata = ReadRecordingMetadata(map["metadata"]);
            return result;
        }
        private static object WriteCreateRecordingRequest(CreateRecordingRequest value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["metadata"] = WriteRecordingMetadata(value.Metadata);
            return map;
        }
        public static RecordingMetadata ParseRecordingMetadata(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("RecordingMetadata", raw); return ReadRecordingMetadata(raw); }
        public static string SerializeRecordingMetadata(RecordingMetadata value) { var json = StrictJson.Stringify(WriteRecordingMetadata(value)); ParseRecordingMetadata(json); return json; }
        private static RecordingMetadata ReadRecordingMetadata(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new RecordingMetadata();
            if (map.ContainsKey("schemaVersion")) result.SchemaVersion = (int)(double)map["schemaVersion"];
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("coordinateFrame")) result.CoordinateFrame = (string)map["coordinateFrame"];
            if (map.ContainsKey("workspace")) result.Workspace = ReadWorkspaceDefinition(map["workspace"]);
            if (map.ContainsKey("jointOrder")) result.JointOrder = ((List<object>)map["jointOrder"]).Select(item => (string)item).ToArray();
            if (map.ContainsKey("nominalSampleHz")) result.NominalSampleHz = (int)(double)map["nominalSampleHz"];
            if (map.ContainsKey("durationMs")) result.DurationMs = (double)(double)map["durationMs"];
            if (map.ContainsKey("markers")) result.Markers = ((List<object>)map["markers"]).Select(item => ReadStepMarker(item)).ToArray();
            if (map.ContainsKey("audio")) result.Audio = (map["audio"] == null ? (AudioAsset)null : ReadAudioAsset(map["audio"]));
            if (map.ContainsKey("source")) result.Source = (string)map["source"];
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteRecordingMetadata(RecordingMetadata value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["id"] = (object)value.Id;
            map["coordinateFrame"] = (object)value.CoordinateFrame;
            map["workspace"] = WriteWorkspaceDefinition(value.Workspace);
            map["jointOrder"] = (value.JointOrder == null ? null : value.JointOrder.Select(item => (object)item).ToList());
            map["nominalSampleHz"] = (object)value.NominalSampleHz;
            map["durationMs"] = (object)value.DurationMs;
            map["markers"] = (value.Markers == null ? null : value.Markers.Select(item => WriteStepMarker(item)).ToList());
            map["audio"] = (value.Audio == null ? null : WriteAudioAsset(value.Audio));
            map["source"] = (object)value.Source;
            return map;
        }
        public static WorkspaceDefinition ParseWorkspaceDefinition(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("WorkspaceDefinition", raw); return ReadWorkspaceDefinition(raw); }
        public static string SerializeWorkspaceDefinition(WorkspaceDefinition value) { var json = StrictJson.Stringify(WriteWorkspaceDefinition(value)); ParseWorkspaceDefinition(json); return json; }
        private static WorkspaceDefinition ReadWorkspaceDefinition(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new WorkspaceDefinition();
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("version")) result.Version = (int)(double)map["version"];
            if (map.ContainsKey("widthM")) result.WidthM = (double)(double)map["widthM"];
            if (map.ContainsKey("depthM")) result.DepthM = (double)(double)map["depthM"];
            if (map.ContainsKey("calibrationMarksM")) result.CalibrationMarksM = ReadCalibrationMarks(map["calibrationMarksM"]);
            if (map.ContainsKey("layoutId")) result.LayoutId = (string)map["layoutId"];
            if (map.ContainsKey("dominantHand")) result.DominantHand = (string)map["dominantHand"];
            if (map.ContainsKey("calibrationMethod")) result.CalibrationMethod = (string)map["calibrationMethod"];
            return result;
        }
        private static object WriteWorkspaceDefinition(WorkspaceDefinition value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["id"] = (object)value.Id;
            map["version"] = (object)value.Version;
            map["widthM"] = (object)value.WidthM;
            map["depthM"] = (object)value.DepthM;
            map["calibrationMarksM"] = WriteCalibrationMarks(value.CalibrationMarksM);
            map["layoutId"] = (object)value.LayoutId;
            map["dominantHand"] = (object)value.DominantHand;
            map["calibrationMethod"] = (object)value.CalibrationMethod;
            return map;
        }
        private static CalibrationMarks ReadCalibrationMarks(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new CalibrationMarks();
            if (map.ContainsKey("A")) result.A = ReadVec3(map["A"]);
            if (map.ContainsKey("B")) result.B = ReadVec3(map["B"]);
            if (map.ContainsKey("C")) result.C = ReadVec3(map["C"]);
            if (map.ContainsKey("D")) result.D = ReadVec3(map["D"]);
            return result;
        }
        private static object WriteCalibrationMarks(CalibrationMarks value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["A"] = WriteVec3(value.A);
            map["B"] = WriteVec3(value.B);
            map["C"] = WriteVec3(value.C);
            map["D"] = WriteVec3(value.D);
            return map;
        }
        private static StepMarker ReadStepMarker(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new StepMarker();
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("tMs")) result.TMs = (double)(double)map["tMs"];
            if (map.ContainsKey("kind")) result.Kind = (string)map["kind"];
            if (map.ContainsKey("source")) result.Source = (string)map["source"];
            return result;
        }
        private static object WriteStepMarker(StepMarker value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["id"] = (object)value.Id;
            map["tMs"] = (object)value.TMs;
            map["kind"] = (object)value.Kind;
            map["source"] = (object)value.Source;
            return map;
        }
        private static AudioAsset ReadAudioAsset(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new AudioAsset();
            if (map.ContainsKey("assetId")) result.AssetId = (string)map["assetId"];
            if (map.ContainsKey("mimeType")) result.MimeType = (string)map["mimeType"];
            if (map.ContainsKey("durationMs")) result.DurationMs = (double)(double)map["durationMs"];
            if (map.ContainsKey("audioStartOffsetMs")) result.AudioStartOffsetMs = (double)(double)map["audioStartOffsetMs"];
            if (map.ContainsKey("syncMethod")) result.SyncMethod = (string)map["syncMethod"];
            if (map.ContainsKey("estimatedSyncErrorMs")) result.EstimatedSyncErrorMs = (map["estimatedSyncErrorMs"] == null ? (double?)null : (double)(double)map["estimatedSyncErrorMs"]);
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteAudioAsset(AudioAsset value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["assetId"] = (object)value.AssetId;
            map["mimeType"] = (object)value.MimeType;
            map["durationMs"] = (object)value.DurationMs;
            map["audioStartOffsetMs"] = (object)value.AudioStartOffsetMs;
            map["syncMethod"] = (object)value.SyncMethod;
            map["estimatedSyncErrorMs"] = (value.EstimatedSyncErrorMs == null ? null : (object)value.EstimatedSyncErrorMs.Value);
            return map;
        }
        public static FinalizeRecordingRequest ParseFinalizeRecordingRequest(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("FinalizeRecordingRequest", raw); return ReadFinalizeRecordingRequest(raw); }
        public static string SerializeFinalizeRecordingRequest(FinalizeRecordingRequest value) { var json = StrictJson.Stringify(WriteFinalizeRecordingRequest(value)); ParseFinalizeRecordingRequest(json); return json; }
        private static FinalizeRecordingRequest ReadFinalizeRecordingRequest(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new FinalizeRecordingRequest();
            if (map.ContainsKey("chunkCount")) result.ChunkCount = (int)(double)map["chunkCount"];
            if (map.ContainsKey("sha256")) result.Sha256 = (string)map["sha256"];
            return result;
        }
        private static object WriteFinalizeRecordingRequest(FinalizeRecordingRequest value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["chunkCount"] = (object)value.ChunkCount;
            map["sha256"] = (object)value.Sha256;
            return map;
        }
        public static GuideContextRef ParseGuideContextRef(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("GuideContextRef", raw); return ReadGuideContextRef(raw); }
        public static string SerializeGuideContextRef(GuideContextRef value) { var json = StrictJson.Stringify(WriteGuideContextRef(value)); ParseGuideContextRef(json); return json; }
        private static GuideContextRef ReadGuideContextRef(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new GuideContextRef();
            if (map.ContainsKey("runId")) result.RunId = (string)map["runId"];
            if (map.ContainsKey("tutorialId")) result.TutorialId = (string)map["tutorialId"];
            if (map.ContainsKey("tutorialRevision")) result.TutorialRevision = (int)(double)map["tutorialRevision"];
            if (map.ContainsKey("stepId")) result.StepId = (string)map["stepId"];
            if (map.ContainsKey("stepRevision")) result.StepRevision = (int)(double)map["stepRevision"];
            if (map.ContainsKey("attemptId")) result.AttemptId = (string)map["attemptId"];
            return result;
        }
        private static object WriteGuideContextRef(GuideContextRef value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["runId"] = (object)value.RunId;
            map["tutorialId"] = (object)value.TutorialId;
            map["tutorialRevision"] = (object)value.TutorialRevision;
            map["stepId"] = (object)value.StepId;
            map["stepRevision"] = (object)value.StepRevision;
            map["attemptId"] = (object)value.AttemptId;
            return map;
        }
        public static GuideEvent ParseGuideEvent(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("GuideEvent", raw); return ReadGuideEvent(raw); }
        public static string SerializeGuideEvent(GuideEvent value) { var json = StrictJson.Stringify(WriteGuideEvent(value)); ParseGuideEvent(json); return json; }
        private static GuideEvent ReadGuideEvent(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new GuideEvent();
            if (map.ContainsKey("schemaVersion")) result.SchemaVersion = (int)(double)map["schemaVersion"];
            if (map.ContainsKey("sessionId")) result.SessionId = (string)map["sessionId"];
            if (map.ContainsKey("runId")) result.RunId = (string)map["runId"];
            if (map.ContainsKey("seq")) result.Seq = (long)(double)map["seq"];
            if (map.ContainsKey("tMs")) result.TMs = (double)(double)map["tMs"];
            if (map.ContainsKey("type")) result.Type = (string)map["type"];
            if (map.ContainsKey("state")) result.State = ReadGuideSnapshot(map["state"]);
            if (map.ContainsKey("stepId")) result.StepId = (string)map["stepId"];
            if (map.ContainsKey("attemptId")) result.AttemptId = (string)map["attemptId"];
            if (map.ContainsKey("evidence")) result.Evidence = (string)map["evidence"];
            if (map.ContainsKey("reason")) result.Reason = (string)map["reason"];
            return result;
        }
        private static object WriteGuideEvent(GuideEvent value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            if (value.Type == "snapshot")
            {
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["sessionId"] = (object)value.SessionId;
            map["runId"] = (object)value.RunId;
            map["seq"] = (object)value.Seq;
            map["tMs"] = (object)value.TMs;
            map["type"] = (object)value.Type;
            map["state"] = WriteGuideSnapshot(value.State);
                return map;
            }
            if (value.Type == "tracking-changed")
            {
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["sessionId"] = (object)value.SessionId;
            map["runId"] = (object)value.RunId;
            map["seq"] = (object)value.Seq;
            map["tMs"] = (object)value.TMs;
            map["type"] = (object)value.Type;
            map["state"] = WriteGuideSnapshot(value.State);
                return map;
            }
            if (value.Type == "step-completed")
            {
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["sessionId"] = (object)value.SessionId;
            map["runId"] = (object)value.RunId;
            map["seq"] = (object)value.Seq;
            map["tMs"] = (object)value.TMs;
            map["type"] = (object)value.Type;
            map["stepId"] = (object)value.StepId;
            map["attemptId"] = (object)value.AttemptId;
            map["evidence"] = (object)value.Evidence;
                return map;
            }
            if (value.Type == "guide-ended")
            {
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["sessionId"] = (object)value.SessionId;
            map["runId"] = (object)value.RunId;
            map["seq"] = (object)value.Seq;
            map["tMs"] = (object)value.TMs;
            map["type"] = (object)value.Type;
            map["reason"] = (object)value.Reason;
                return map;
            }
            throw new ContractException("Unknown union discriminator");
        }
        public static GuideSnapshot ParseGuideSnapshot(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("GuideSnapshot", raw); return ReadGuideSnapshot(raw); }
        public static string SerializeGuideSnapshot(GuideSnapshot value) { var json = StrictJson.Stringify(WriteGuideSnapshot(value)); ParseGuideSnapshot(json); return json; }
        private static GuideSnapshot ReadGuideSnapshot(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new GuideSnapshot();
            if (map.ContainsKey("phase")) result.Phase = (string)map["phase"];
            if (map.ContainsKey("tutorialId")) result.TutorialId = (string)map["tutorialId"];
            if (map.ContainsKey("tutorialRevision")) result.TutorialRevision = (int)(double)map["tutorialRevision"];
            if (map.ContainsKey("stepId")) result.StepId = (map["stepId"] == null ? (string)null : (string)map["stepId"]);
            if (map.ContainsKey("stepRevision")) result.StepRevision = (int)(double)map["stepRevision"];
            if (map.ContainsKey("attemptId")) result.AttemptId = (map["attemptId"] == null ? (string)null : (string)map["attemptId"]);
            if (map.ContainsKey("dwellProgress")) result.DwellProgress = (double)(double)map["dwellProgress"];
            if (map.ContainsKey("pathProgress")) result.PathProgress = (double)(double)map["pathProgress"];
            if (map.ContainsKey("nextGateByHand")) result.NextGateByHand = ReadNextGateByHand(map["nextGateByHand"]);
            if (map.ContainsKey("calibrationValid")) result.CalibrationValid = (bool)map["calibrationValid"];
            if (map.ContainsKey("tracking")) result.Tracking = ReadHandTracking(map["tracking"]);
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteGuideSnapshot(GuideSnapshot value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["phase"] = (object)value.Phase;
            map["tutorialId"] = (object)value.TutorialId;
            map["tutorialRevision"] = (object)value.TutorialRevision;
            map["stepId"] = (value.StepId == null ? null : (object)value.StepId);
            map["stepRevision"] = (object)value.StepRevision;
            map["attemptId"] = (value.AttemptId == null ? null : (object)value.AttemptId);
            map["dwellProgress"] = (object)value.DwellProgress;
            map["pathProgress"] = (object)value.PathProgress;
            map["nextGateByHand"] = WriteNextGateByHand(value.NextGateByHand);
            map["calibrationValid"] = (object)value.CalibrationValid;
            map["tracking"] = WriteHandTracking(value.Tracking);
            return map;
        }
        private static NextGateByHand ReadNextGateByHand(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new NextGateByHand();
            if (map.ContainsKey("left")) result.Left = (int)(double)map["left"];
            if (map.ContainsKey("right")) result.Right = (int)(double)map["right"];
            return result;
        }
        private static object WriteNextGateByHand(NextGateByHand value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            if (value.Left != null) map["left"] = (object)value.Left.Value;
            if (value.Right != null) map["right"] = (object)value.Right.Value;
            return map;
        }
        private static HandTracking ReadHandTracking(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new HandTracking();
            if (map.ContainsKey("left")) result.Left = (string)map["left"];
            if (map.ContainsKey("right")) result.Right = (string)map["right"];
            return result;
        }
        private static object WriteHandTracking(HandTracking value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["left"] = (object)value.Left;
            map["right"] = (object)value.Right;
            return map;
        }
        public static HandSample ParseHandSample(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("HandSample", raw); return ReadHandSample(raw); }
        public static string SerializeHandSample(HandSample value) { var json = StrictJson.Stringify(WriteHandSample(value)); ParseHandSample(json); return json; }
        private static HandSample ReadHandSample(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new HandSample();
            if (map.ContainsKey("status")) result.Status = (string)map["status"];
            if (map.ContainsKey("reason")) result.Reason = (string)map["reason"];
            if (map.ContainsKey("joints")) result.Joints = ((Dictionary<string, object>)map["joints"]).ToDictionary(pair => pair.Key, pair => ReadPose(pair.Value), StringComparer.Ordinal);
            return result;
        }
        private static object WriteHandSample(HandSample value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            if (value.Status == "missing")
            {
            map["status"] = (object)value.Status;
            map["reason"] = (object)value.Reason;
                return map;
            }
            if (value.Status == "valid")
            {
            map["status"] = (object)value.Status;
            map["joints"] = (value.Joints == null ? null : value.Joints.ToDictionary(pair => pair.Key, pair => WritePose(pair.Value), StringComparer.Ordinal));
                return map;
            }
            throw new ContractException("Unknown union discriminator");
        }
        public static HandTarget ParseHandTarget(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("HandTarget", raw); return ReadHandTarget(raw); }
        public static string SerializeHandTarget(HandTarget value) { var json = StrictJson.Stringify(WriteHandTarget(value)); ParseHandTarget(json); return json; }
        private static HandTarget ReadHandTarget(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new HandTarget();
            if (map.ContainsKey("side")) result.Side = (string)map["side"];
            if (map.ContainsKey("joint")) result.Joint = (string)map["joint"];
            if (map.ContainsKey("startPose")) result.StartPose = ReadPose(map["startPose"]);
            if (map.ContainsKey("checkpointPose")) result.CheckpointPose = ReadPose(map["checkpointPose"]);
            if (map.ContainsKey("positionToleranceM")) result.PositionToleranceM = (double)(double)map["positionToleranceM"];
            if (map.ContainsKey("orientationToleranceRad")) result.OrientationToleranceRad = (map["orientationToleranceRad"] == null ? (double?)null : (double)(double)map["orientationToleranceRad"]);
            if (map.ContainsKey("gesture")) result.Gesture = (string)map["gesture"];
            if (map.ContainsKey("motionGates")) result.MotionGates = ((List<object>)map["motionGates"]).Select(item => ReadMotionGate(item)).ToArray();
            if (map.ContainsKey("pathCorridorM")) result.PathCorridorM = (double)(double)map["pathCorridorM"];
            return result;
        }
        private static object WriteHandTarget(HandTarget value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["side"] = (object)value.Side;
            map["joint"] = (object)value.Joint;
            map["startPose"] = WritePose(value.StartPose);
            map["checkpointPose"] = WritePose(value.CheckpointPose);
            map["positionToleranceM"] = (object)value.PositionToleranceM;
            map["orientationToleranceRad"] = (value.OrientationToleranceRad == null ? null : (object)value.OrientationToleranceRad.Value);
            map["gesture"] = (object)value.Gesture;
            map["motionGates"] = (value.MotionGates == null ? null : value.MotionGates.Select(item => WriteMotionGate(item)).ToList());
            map["pathCorridorM"] = (object)value.PathCorridorM;
            return map;
        }
        public static MotionGate ParseMotionGate(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("MotionGate", raw); return ReadMotionGate(raw); }
        public static string SerializeMotionGate(MotionGate value) { var json = StrictJson.Stringify(WriteMotionGate(value)); ParseMotionGate(json); return json; }
        private static MotionGate ReadMotionGate(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new MotionGate();
            if (map.ContainsKey("frameIndex")) result.FrameIndex = (int)(double)map["frameIndex"];
            if (map.ContainsKey("positionM")) result.PositionM = ReadVec3(map["positionM"]);
            if (map.ContainsKey("toleranceM")) result.ToleranceM = (double)(double)map["toleranceM"];
            if (map.ContainsKey("dwellMs")) result.DwellMs = (double)(double)map["dwellMs"];
            return result;
        }
        private static object WriteMotionGate(MotionGate value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["frameIndex"] = (object)value.FrameIndex;
            map["positionM"] = WriteVec3(value.PositionM);
            map["toleranceM"] = (object)value.ToleranceM;
            map["dwellMs"] = (object)value.DwellMs;
            return map;
        }
        public static InspectionRequest ParseInspectionRequest(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("InspectionRequest", raw); return ReadInspectionRequest(raw); }
        public static string SerializeInspectionRequest(InspectionRequest value) { var json = StrictJson.Stringify(WriteInspectionRequest(value)); ParseInspectionRequest(json); return json; }
        private static InspectionRequest ReadInspectionRequest(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new InspectionRequest();
            if (map.ContainsKey("runId")) result.RunId = (string)map["runId"];
            if (map.ContainsKey("tutorialId")) result.TutorialId = (string)map["tutorialId"];
            if (map.ContainsKey("tutorialRevision")) result.TutorialRevision = (int)(double)map["tutorialRevision"];
            if (map.ContainsKey("stepId")) result.StepId = (string)map["stepId"];
            if (map.ContainsKey("stepRevision")) result.StepRevision = (int)(double)map["stepRevision"];
            if (map.ContainsKey("attemptId")) result.AttemptId = (string)map["attemptId"];
            if (map.ContainsKey("requestId")) result.RequestId = (string)map["requestId"];
            if (map.ContainsKey("liveSessionId")) result.LiveSessionId = (string)map["liveSessionId"];
            if (map.ContainsKey("sessionGeneration")) result.SessionGeneration = (int)(double)map["sessionGeneration"];
            if (map.ContainsKey("requestEpoch")) result.RequestEpoch = (int)(double)map["requestEpoch"];
            if (map.ContainsKey("delegationId")) result.DelegationId = (map["delegationId"] == null ? (string)null : (string)map["delegationId"]);
            if (map.ContainsKey("question")) result.Question = (string)map["question"];
            if (map.ContainsKey("referenceIds")) result.ReferenceIds = ((List<object>)map["referenceIds"]).Select(item => (string)item).ToArray();
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteInspectionRequest(InspectionRequest value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["runId"] = (object)value.RunId;
            map["tutorialId"] = (object)value.TutorialId;
            map["tutorialRevision"] = (object)value.TutorialRevision;
            map["stepId"] = (object)value.StepId;
            map["stepRevision"] = (object)value.StepRevision;
            map["attemptId"] = (object)value.AttemptId;
            map["requestId"] = (object)value.RequestId;
            map["liveSessionId"] = (object)value.LiveSessionId;
            map["sessionGeneration"] = (object)value.SessionGeneration;
            map["requestEpoch"] = (object)value.RequestEpoch;
            map["delegationId"] = (value.DelegationId == null ? null : (object)value.DelegationId);
            map["question"] = (object)value.Question;
            map["referenceIds"] = (value.ReferenceIds == null ? null : value.ReferenceIds.Select(item => (object)item).ToList());
            return map;
        }
        public static InspectionResult ParseInspectionResult(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("InspectionResult", raw); return ReadInspectionResult(raw); }
        public static string SerializeInspectionResult(InspectionResult value) { var json = StrictJson.Stringify(WriteInspectionResult(value)); ParseInspectionResult(json); return json; }
        private static InspectionResult ReadInspectionResult(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new InspectionResult();
            if (map.ContainsKey("request")) result.Request = ReadInspectionRequest(map["request"]);
            if (map.ContainsKey("observationId")) result.ObservationId = (map["observationId"] == null ? (string)null : (string)map["observationId"]);
            if (map.ContainsKey("referenceIds")) result.ReferenceIds = ((List<object>)map["referenceIds"]).Select(item => (string)item).ToArray();
            if (map.ContainsKey("assessment")) result.Assessment = ReadCoachAssessment(map["assessment"]);
            if (map.ContainsKey("provenance")) result.Provenance = (string)map["provenance"];
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteInspectionResult(InspectionResult value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["request"] = WriteInspectionRequest(value.Request);
            map["observationId"] = (value.ObservationId == null ? null : (object)value.ObservationId);
            map["referenceIds"] = (value.ReferenceIds == null ? null : value.ReferenceIds.Select(item => (object)item).ToList());
            map["assessment"] = WriteCoachAssessment(value.Assessment);
            map["provenance"] = (object)value.Provenance;
            return map;
        }
        public static MotionChunk ParseMotionChunk(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("MotionChunk", raw); return ReadMotionChunk(raw); }
        public static string SerializeMotionChunk(MotionChunk value) { var json = StrictJson.Stringify(WriteMotionChunk(value)); ParseMotionChunk(json); return json; }
        private static MotionChunk ReadMotionChunk(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new MotionChunk();
            if (map.ContainsKey("frames")) result.Frames = ((List<object>)map["frames"]).Select(item => ReadMotionFrame(item)).ToArray();
            if (map.ContainsKey("sha256")) result.Sha256 = (string)map["sha256"];
            return result;
        }
        private static object WriteMotionChunk(MotionChunk value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["frames"] = (value.Frames == null ? null : value.Frames.Select(item => WriteMotionFrame(item)).ToList());
            map["sha256"] = (object)value.Sha256;
            return map;
        }
        public static MotionFrame ParseMotionFrame(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("MotionFrame", raw); return ReadMotionFrame(raw); }
        public static string SerializeMotionFrame(MotionFrame value) { var json = StrictJson.Stringify(WriteMotionFrame(value)); ParseMotionFrame(json); return json; }
        private static MotionFrame ReadMotionFrame(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new MotionFrame();
            if (map.ContainsKey("tMs")) result.TMs = (double)(double)map["tMs"];
            if (map.ContainsKey("hands")) result.Hands = ReadHandSamples(map["hands"]);
            if (map.ContainsKey("head")) result.Head = (map["head"] == null ? (CanonicalPose?)null : ReadPose(map["head"]));
            return result;
        }
        private static object WriteMotionFrame(MotionFrame value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["tMs"] = (object)value.TMs;
            map["hands"] = WriteHandSamples(value.Hands);
            map["head"] = (value.Head == null ? null : WritePose(value.Head.Value));
            return map;
        }
        private static HandSamples ReadHandSamples(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new HandSamples();
            if (map.ContainsKey("left")) result.Left = ReadHandSample(map["left"]);
            if (map.ContainsKey("right")) result.Right = ReadHandSample(map["right"]);
            return result;
        }
        private static object WriteHandSamples(HandSamples value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["left"] = WriteHandSample(value.Left);
            map["right"] = WriteHandSample(value.Right);
            return map;
        }
        public static NativeCaptureSidecar ParseNativeCaptureSidecar(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("NativeCaptureSidecar", raw); return ReadNativeCaptureSidecar(raw); }
        public static string SerializeNativeCaptureSidecar(NativeCaptureSidecar value) { var json = StrictJson.Stringify(WriteNativeCaptureSidecar(value)); ParseNativeCaptureSidecar(json); return json; }
        private static NativeCaptureSidecar ReadNativeCaptureSidecar(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new NativeCaptureSidecar();
            if (map.ContainsKey("schemaVersion")) result.SchemaVersion = (int)(double)map["schemaVersion"];
            if (map.ContainsKey("recordingId")) result.RecordingId = (string)map["recordingId"];
            if (map.ContainsKey("recordingHash")) result.RecordingHash = (string)map["recordingHash"];
            if (map.ContainsKey("trackingSessionId")) result.TrackingSessionId = (string)map["trackingSessionId"];
            if (map.ContainsKey("originRevision")) result.OriginRevision = (int)(double)map["originRevision"];
            if (map.ContainsKey("provider")) result.Provider = (string)map["provider"];
            if (map.ContainsKey("editorVersion")) result.EditorVersion = (string)map["editorVersion"];
            if (map.ContainsKey("sdkVersion")) result.SdkVersion = (string)map["sdkVersion"];
            if (map.ContainsKey("skeleton")) result.Skeleton = (string)map["skeleton"];
            if (map.ContainsKey("adapterVersion")) result.AdapterVersion = (string)map["adapterVersion"];
            if (map.ContainsKey("clock")) result.Clock = ReadClockMapping(map["clock"]);
            if (map.ContainsKey("confidencePolicy")) result.ConfidencePolicy = (string)map["confidencePolicy"];
            if (map.ContainsKey("source")) result.Source = (string)map["source"];
            return result;
        }
        private static object WriteNativeCaptureSidecar(NativeCaptureSidecar value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["recordingId"] = (object)value.RecordingId;
            map["recordingHash"] = (object)value.RecordingHash;
            map["trackingSessionId"] = (object)value.TrackingSessionId;
            map["originRevision"] = (object)value.OriginRevision;
            map["provider"] = (object)value.Provider;
            map["editorVersion"] = (object)value.EditorVersion;
            map["sdkVersion"] = (object)value.SdkVersion;
            map["skeleton"] = (object)value.Skeleton;
            map["adapterVersion"] = (object)value.AdapterVersion;
            map["clock"] = WriteClockMapping(value.Clock);
            map["confidencePolicy"] = (object)value.ConfidencePolicy;
            map["source"] = (object)value.Source;
            return map;
        }
        public static Recording ParseRecording(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("Recording", raw); return ReadRecording(raw); }
        public static string SerializeRecording(Recording value) { var json = StrictJson.Stringify(WriteRecording(value)); ParseRecording(json); return json; }
        private static Recording ReadRecording(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new Recording();
            if (map.ContainsKey("schemaVersion")) result.SchemaVersion = (int)(double)map["schemaVersion"];
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("coordinateFrame")) result.CoordinateFrame = (string)map["coordinateFrame"];
            if (map.ContainsKey("workspace")) result.Workspace = ReadWorkspaceDefinition(map["workspace"]);
            if (map.ContainsKey("jointOrder")) result.JointOrder = ((List<object>)map["jointOrder"]).Select(item => (string)item).ToArray();
            if (map.ContainsKey("nominalSampleHz")) result.NominalSampleHz = (int)(double)map["nominalSampleHz"];
            if (map.ContainsKey("durationMs")) result.DurationMs = (double)(double)map["durationMs"];
            if (map.ContainsKey("frames")) result.Frames = ((List<object>)map["frames"]).Select(item => ReadMotionFrame(item)).ToArray();
            if (map.ContainsKey("markers")) result.Markers = ((List<object>)map["markers"]).Select(item => ReadStepMarker(item)).ToArray();
            if (map.ContainsKey("audio")) result.Audio = (map["audio"] == null ? (AudioAsset)null : ReadAudioAsset(map["audio"]));
            if (map.ContainsKey("source")) result.Source = (string)map["source"];
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteRecording(Recording value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["id"] = (object)value.Id;
            map["coordinateFrame"] = (object)value.CoordinateFrame;
            map["workspace"] = WriteWorkspaceDefinition(value.Workspace);
            map["jointOrder"] = (value.JointOrder == null ? null : value.JointOrder.Select(item => (object)item).ToList());
            map["nominalSampleHz"] = (object)value.NominalSampleHz;
            map["durationMs"] = (object)value.DurationMs;
            map["frames"] = (value.Frames == null ? null : value.Frames.Select(item => WriteMotionFrame(item)).ToList());
            map["markers"] = (value.Markers == null ? null : value.Markers.Select(item => WriteStepMarker(item)).ToList());
            map["audio"] = (value.Audio == null ? null : WriteAudioAsset(value.Audio));
            map["source"] = (object)value.Source;
            return map;
        }
        public static SceneObservation ParseSceneObservation(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("SceneObservation", raw); return ReadSceneObservation(raw); }
        public static string SerializeSceneObservation(SceneObservation value) { var json = StrictJson.Stringify(WriteSceneObservation(value)); ParseSceneObservation(json); return json; }
        private static SceneObservation ReadSceneObservation(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new SceneObservation();
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("requestId")) result.RequestId = (string)map["requestId"];
            if (map.ContainsKey("captureNonce")) result.CaptureNonce = (string)map["captureNonce"];
            if (map.ContainsKey("sourceSessionId")) result.SourceSessionId = (string)map["sourceSessionId"];
            if (map.ContainsKey("source")) result.Source = (string)map["source"];
            if (map.ContainsKey("assetId")) result.AssetId = (string)map["assetId"];
            if (map.ContainsKey("sourceFrameSeq")) result.SourceFrameSeq = (long)(double)map["sourceFrameSeq"];
            if (map.ContainsKey("captureAgeAtSendMs")) result.CaptureAgeAtSendMs = (double)(double)map["captureAgeAtSendMs"];
            if (map.ContainsKey("receivedAtServerMonoMs")) result.ReceivedAtServerMonoMs = (double)(double)map["receivedAtServerMonoMs"];
            return result;
        }
        private static object WriteSceneObservation(SceneObservation value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["id"] = (object)value.Id;
            map["requestId"] = (object)value.RequestId;
            map["captureNonce"] = (object)value.CaptureNonce;
            map["sourceSessionId"] = (object)value.SourceSessionId;
            map["source"] = (object)value.Source;
            map["assetId"] = (object)value.AssetId;
            map["sourceFrameSeq"] = (object)value.SourceFrameSeq;
            map["captureAgeAtSendMs"] = (object)value.CaptureAgeAtSendMs;
            map["receivedAtServerMonoMs"] = (object)value.ReceivedAtServerMonoMs;
            return map;
        }
        public static SceneReferenceManifest ParseSceneReferenceManifest(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("SceneReferenceManifest", raw); return ReadSceneReferenceManifest(raw); }
        public static string SerializeSceneReferenceManifest(SceneReferenceManifest value) { var json = StrictJson.Stringify(WriteSceneReferenceManifest(value)); ParseSceneReferenceManifest(json); return json; }
        private static SceneReferenceManifest ReadSceneReferenceManifest(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new SceneReferenceManifest();
            if (map.ContainsKey("schemaVersion")) result.SchemaVersion = (int)(double)map["schemaVersion"];
            if (map.ContainsKey("recordingId")) result.RecordingId = (string)map["recordingId"];
            if (map.ContainsKey("recordingHash")) result.RecordingHash = (string)map["recordingHash"];
            if (map.ContainsKey("tutorialId")) result.TutorialId = (string)map["tutorialId"];
            if (map.ContainsKey("tutorialRevision")) result.TutorialRevision = (int)(double)map["tutorialRevision"];
            if (map.ContainsKey("references")) result.References = ((List<object>)map["references"]).Select(item => ReadStepSceneReference(item)).ToArray();
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteSceneReferenceManifest(SceneReferenceManifest value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["recordingId"] = (object)value.RecordingId;
            map["recordingHash"] = (object)value.RecordingHash;
            map["tutorialId"] = (object)value.TutorialId;
            map["tutorialRevision"] = (object)value.TutorialRevision;
            map["references"] = (value.References == null ? null : value.References.Select(item => WriteStepSceneReference(item)).ToList());
            return map;
        }
        public static StepSceneReference ParseStepSceneReference(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("StepSceneReference", raw); return ReadStepSceneReference(raw); }
        public static string SerializeStepSceneReference(StepSceneReference value) { var json = StrictJson.Stringify(WriteStepSceneReference(value)); ParseStepSceneReference(json); return json; }
        private static StepSceneReference ReadStepSceneReference(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new StepSceneReference();
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("recordingId")) result.RecordingId = (string)map["recordingId"];
            if (map.ContainsKey("recordingHash")) result.RecordingHash = (string)map["recordingHash"];
            if (map.ContainsKey("tutorialId")) result.TutorialId = (string)map["tutorialId"];
            if (map.ContainsKey("tutorialRevision")) result.TutorialRevision = (int)(double)map["tutorialRevision"];
            if (map.ContainsKey("stepId")) result.StepId = (string)map["stepId"];
            if (map.ContainsKey("assetId")) result.AssetId = (string)map["assetId"];
            if (map.ContainsKey("source")) result.Source = (string)map["source"];
            if (map.ContainsKey("visibleOutcome")) result.VisibleOutcome = (string)map["visibleOutcome"];
            return result;
        }
        private static object WriteStepSceneReference(StepSceneReference value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["id"] = (object)value.Id;
            map["recordingId"] = (object)value.RecordingId;
            map["recordingHash"] = (object)value.RecordingHash;
            map["tutorialId"] = (object)value.TutorialId;
            map["tutorialRevision"] = (object)value.TutorialRevision;
            map["stepId"] = (object)value.StepId;
            map["assetId"] = (object)value.AssetId;
            map["source"] = (object)value.Source;
            map["visibleOutcome"] = (object)value.VisibleOutcome;
            return map;
        }
        public static Tutorial ParseTutorial(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("Tutorial", raw); return ReadTutorial(raw); }
        public static string SerializeTutorial(Tutorial value) { var json = StrictJson.Stringify(WriteTutorial(value)); ParseTutorial(json); return json; }
        private static Tutorial ReadTutorial(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new Tutorial();
            if (map.ContainsKey("schemaVersion")) result.SchemaVersion = (int)(double)map["schemaVersion"];
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("revision")) result.Revision = (int)(double)map["revision"];
            if (map.ContainsKey("recordingId")) result.RecordingId = (string)map["recordingId"];
            if (map.ContainsKey("recordingHash")) result.RecordingHash = (string)map["recordingHash"];
            if (map.ContainsKey("workspace")) result.Workspace = ReadWorkspaceDefinition(map["workspace"]);
            if (map.ContainsKey("status")) result.Status = (string)map["status"];
            if (map.ContainsKey("steps")) result.Steps = ((List<object>)map["steps"]).Select(item => ReadTutorialStep(item)).ToArray();
            if (map.ContainsKey("provenance")) result.Provenance = ReadTutorialProvenance(map["provenance"]);
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteTutorial(Tutorial value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["schemaVersion"] = (object)value.SchemaVersion;
            map["id"] = (object)value.Id;
            map["revision"] = (object)value.Revision;
            map["recordingId"] = (object)value.RecordingId;
            map["recordingHash"] = (object)value.RecordingHash;
            map["workspace"] = WriteWorkspaceDefinition(value.Workspace);
            map["status"] = (object)value.Status;
            map["steps"] = (value.Steps == null ? null : value.Steps.Select(item => WriteTutorialStep(item)).ToList());
            map["provenance"] = WriteTutorialProvenance(value.Provenance);
            return map;
        }
        public static TutorialStep ParseTutorialStep(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("TutorialStep", raw); return ReadTutorialStep(raw); }
        public static string SerializeTutorialStep(TutorialStep value) { var json = StrictJson.Stringify(WriteTutorialStep(value)); ParseTutorialStep(json); return json; }
        private static TutorialStep ReadTutorialStep(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new TutorialStep();
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("startFrame")) result.StartFrame = (int)(double)map["startFrame"];
            if (map.ContainsKey("endFrameExclusive")) result.EndFrameExclusive = (int)(double)map["endFrameExclusive"];
            if (map.ContainsKey("checkpointFrame")) result.CheckpointFrame = (int)(double)map["checkpointFrame"];
            if (map.ContainsKey("title")) result.Title = (string)map["title"];
            if (map.ContainsKey("instruction")) result.Instruction = (string)map["instruction"];
            if (map.ContainsKey("targets")) result.Targets = ((List<object>)map["targets"]).Select(item => ReadHandTarget(item)).ToArray();
            if (map.ContainsKey("dwellMs")) result.DwellMs = (double)(double)map["dwellMs"];
            if (map.ContainsKey("startDwellMs")) result.StartDwellMs = (double)(double)map["startDwellMs"];
            if (map.ContainsKey("completionMode")) result.CompletionMode = (string)map["completionMode"];
            if (map.ContainsKey("narrationSpanIds")) result.NarrationSpanIds = ((List<object>)map["narrationSpanIds"]).Select(item => (string)item).ToArray();
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteTutorialStep(TutorialStep value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["id"] = (object)value.Id;
            map["startFrame"] = (object)value.StartFrame;
            map["endFrameExclusive"] = (object)value.EndFrameExclusive;
            map["checkpointFrame"] = (object)value.CheckpointFrame;
            map["title"] = (object)value.Title;
            map["instruction"] = (object)value.Instruction;
            map["targets"] = (value.Targets == null ? null : value.Targets.Select(item => WriteHandTarget(item)).ToList());
            map["dwellMs"] = (object)value.DwellMs;
            map["startDwellMs"] = (object)value.StartDwellMs;
            map["completionMode"] = (object)value.CompletionMode;
            map["narrationSpanIds"] = (value.NarrationSpanIds == null ? null : value.NarrationSpanIds.Select(item => (object)item).ToList());
            return map;
        }
        public static TutorialProvenance ParseTutorialProvenance(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("TutorialProvenance", raw); return ReadTutorialProvenance(raw); }
        public static string SerializeTutorialProvenance(TutorialProvenance value) { var json = StrictJson.Stringify(WriteTutorialProvenance(value)); ParseTutorialProvenance(json); return json; }
        private static TutorialProvenance ReadTutorialProvenance(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new TutorialProvenance();
            if (map.ContainsKey("segmentation")) result.Segmentation = (string)map["segmentation"];
            if (map.ContainsKey("labels")) result.Labels = (string)map["labels"];
            if (map.ContainsKey("model")) result.Model = (map["model"] == null ? (string)null : (string)map["model"]);
            if (map.ContainsKey("promptVersion")) result.PromptVersion = (string)map["promptVersion"];
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteTutorialProvenance(TutorialProvenance value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["segmentation"] = (object)value.Segmentation;
            map["labels"] = (object)value.Labels;
            map["model"] = (value.Model == null ? null : (object)value.Model);
            map["promptVersion"] = (object)value.PromptVersion;
            return map;
        }
        public static TutorialDraftEdit ParseTutorialDraftEdit(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("TutorialDraftEdit", raw); return ReadTutorialDraftEdit(raw); }
        public static string SerializeTutorialDraftEdit(TutorialDraftEdit value) { var json = StrictJson.Stringify(WriteTutorialDraftEdit(value)); ParseTutorialDraftEdit(json); return json; }
        private static TutorialDraftEdit ReadTutorialDraftEdit(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new TutorialDraftEdit();
            if (map.ContainsKey("baseRevision")) result.BaseRevision = (int)(double)map["baseRevision"];
            if (map.ContainsKey("steps")) result.Steps = ((List<object>)map["steps"]).Select(item => ReadTutorialDraftStep(item)).ToArray();
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteTutorialDraftEdit(TutorialDraftEdit value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["baseRevision"] = (object)value.BaseRevision;
            map["steps"] = (value.Steps == null ? null : value.Steps.Select(item => WriteTutorialDraftStep(item)).ToList());
            return map;
        }
        public static TutorialDraftStep ParseTutorialDraftStep(string json) { var raw = StrictJson.Parse(json); ContractShape.Validate("TutorialDraftStep", raw); return ReadTutorialDraftStep(raw); }
        public static string SerializeTutorialDraftStep(TutorialDraftStep value) { var json = StrictJson.Stringify(WriteTutorialDraftStep(value)); ParseTutorialDraftStep(json); return json; }
        private static TutorialDraftStep ReadTutorialDraftStep(object value)
        {
            var map = (Dictionary<string, object>)value;
            var result = new TutorialDraftStep();
            if (map.ContainsKey("id")) result.Id = (string)map["id"];
            if (map.ContainsKey("startFrame")) result.StartFrame = (int)(double)map["startFrame"];
            if (map.ContainsKey("endFrameExclusive")) result.EndFrameExclusive = (int)(double)map["endFrameExclusive"];
            if (map.ContainsKey("checkpointFrame")) result.CheckpointFrame = (int)(double)map["checkpointFrame"];
            if (map.ContainsKey("activeHands")) result.ActiveHands = ((List<object>)map["activeHands"]).Select(item => (string)item).ToArray();
            if (map.ContainsKey("completionMode")) result.CompletionMode = (string)map["completionMode"];
            if (map.ContainsKey("title")) result.Title = (string)map["title"];
            if (map.ContainsKey("instruction")) result.Instruction = (string)map["instruction"];
            ContractValidation.Validate(result);
            return result;
        }
        private static object WriteTutorialDraftStep(TutorialDraftStep value)
        {
            if (value == null) return null;
            var map = new Dictionary<string, object>(StringComparer.Ordinal);
            map["id"] = (object)value.Id;
            map["startFrame"] = (object)value.StartFrame;
            map["endFrameExclusive"] = (object)value.EndFrameExclusive;
            map["checkpointFrame"] = (object)value.CheckpointFrame;
            map["activeHands"] = (value.ActiveHands == null ? null : value.ActiveHands.Select(item => (object)item).ToList());
            map["completionMode"] = (object)value.CompletionMode;
            map["title"] = (object)value.Title;
            map["instruction"] = (object)value.Instruction;
            return map;
        }
    }
}
