import { expect, test } from '@playwright/test';
import { issueBrowserCode } from './pairing.js';

test('browser pairing, import, four-step review, immutable finalize and reload', async ({ page, request, browser }) => {
  test.setTimeout(90_000);
  const errors: string[]=[]; page.on('pageerror',error=>errors.push(error.message));
  const code=await issueBrowserCode('author');
  await page.goto('/'); await page.getByRole('button',{name:'Author a guide',exact:true}).click();
  await page.getByLabel('Pairing code').fill(code); await page.getByRole('button',{name:'Connect workspace'}).click();
  await expect(page.locator('#pair-state')).toHaveText('Connected as author.');
  await page.getByRole('button',{name:'Import four-step sample'}).click();
  await expect(page.locator('#step-strip li')).toHaveCount(4,{timeout:30_000});
  await expect(page.locator('#author-source')).toHaveText('Synthetic recording');
  for(let index=0;index<4;index++) {
    await page.locator('#step-strip button').nth(index).click();
    await page.getByLabel('Title',{exact:true}).fill(`Place part ${index+1}`);
    await page.getByLabel('Instruction',{exact:true}).fill(`Move large part ${index+1} across the mat, then hold still.`);
    await page.getByRole('combobox',{name:'Completion',exact:true}).selectOption('path-and-pose');
    await page.getByRole('button',{name:'Apply step edits'}).click();
  }
  await page.getByRole('button',{name:'Save reviewed draft'}).click();
  await expect(page.locator('#author-status')).toContainText('Reviewed draft saved');
  await page.getByRole('button',{name:'Show checkpoint',exact:true}).click();
  await expect(page.locator('#frame-label')).toContainText('359');
  await page.getByRole('button',{name:'Finalize guide',exact:true}).click();
  await expect(page.locator('#author-status')).toContainText('Guide finalized');
  await expect(page.locator('#step-title')).toBeDisabled();
  await page.screenshot({path:'test-results/authoring-review.png',fullPage:true});
  const savedId = await page.getByLabel('Saved guides').inputValue();
  await page.reload(); await page.getByRole('button',{name:'Author a guide',exact:true}).click();
  await page.getByRole('button',{name:'Reload saved guides'}).click();
  await expect(page.locator(`#tutorial-library option[value="${savedId}"]`)).toHaveCount(1);
  const id=savedId; await page.getByLabel('Saved guides').selectOption(id!);
  await expect(page.locator('#author-status')).toContainText('Finalized guide loaded');
  await expect(page.locator('#step-strip li')).toHaveCount(4);
  await page.getByRole('button',{name:'Create pairing code',exact:true}).click();
  await expect(page.locator('#invite-code')).toHaveText(/^[0-9]{8}$/);
  const inviteCode = (await page.locator('#invite-code').textContent())!;
  const paired = await request.post('/api/pair', { data:{ code:inviteCode,client:'native' } }); const learner = await paired.json() as {token:string;sessionId:string};
  await page.getByRole('combobox',{name:'New device',exact:true}).selectOption('spectator');
  await page.getByRole('combobox',{name:'Client',exact:true}).selectOption('browser');
  await page.getByRole('button',{name:'Create pairing code',exact:true}).click();
  await expect(page.locator('#invite-code')).not.toHaveText(inviteCode);
  const spectatorCode=(await page.locator('#invite-code').textContent())!;
  const spectatorContext=await browser.newContext();
  const spectator=await spectatorContext.newPage();
  await spectator.goto(page.url());
  await spectator.getByRole('button',{name:'Spectator',exact:true}).click();
  await spectator.getByLabel('Pairing code').fill(spectatorCode);
  await spectator.getByRole('button',{name:'Connect workspace'}).click();
  await expect(spectator.locator('#pair-state')).toHaveText('Connected as spectator.');
  await expect(spectator.locator('#spectator-connection')).toHaveText('Stale or disconnected');
  const published = await request.post('/api/guide-events', { headers:{Authorization:`Bearer ${learner.token}`},data:{schemaVersion:1,type:'snapshot',sessionId:learner.sessionId,runId:'browser-smoke-run',seq:1,tMs:100,state:{phase:'guiding',tutorialId:id,tutorialRevision:3,stepId:'step-1',stepRevision:1,attemptId:'attempt-1',dwellProgress:0,pathProgress:.4,nextGateByHand:{right:1},calibrationValid:true,tracking:{left:'missing',right:'valid'}}} });
  expect(published.status()).toBe(204);
  await expect(spectator.locator('#spectator-connection')).toHaveText('Live headset state');
  await expect(spectator.locator('#spectator-step')).toContainText('Place part 1');
  await spectator.getByRole('button',{name:'Reconnect spectator'}).click();
  await expect(spectator.locator('#spectator-step')).toContainText('Place part 1');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await spectatorContext.close();
});
