using System;
using Trail.Runtime.Network;
static void Reject(Action action) { try { action(); } catch (ArgumentException) { return; } throw new Exception("Expected rejection"); }
var secure = new ConnectionPolicy("https://trail.example", false);
if (secure.Endpoint("/api/session").AbsoluteUri != "https://trail.example/api/session") throw new Exception("Wrong endpoint");
foreach (var origin in new[] { "http://trail.example", "http://127.0.0.1", "https://token@trail.example", "https://trail.example/api", "https://trail.example?token=secret" }) Reject(() => new ConnectionPolicy(origin, false));
foreach (var origin in new[] { "http://127.0.0.1:3401", "http://[::1]:3401", "http://localhost:3401" }) _ = new ConnectionPolicy(origin, true);
Reject(() => new ConnectionPolicy("http://localhost.evil.example", true));
foreach (var path in new[] { "//evil.example/api", "/api/../secret", "/api/%2e%2e/secret", "/api/session?token=secret", "/api/session#secret", "/outside" }) Reject(() => secure.Endpoint(path));
var session = new PairedSession(); var token = new string('a', 43); var id = Guid.NewGuid().ToString();
session.Accept(token, "learner", id, 5000, 1000);
if (!session.IsAvailable(4999) || session.IsAvailable(5000)) throw new Exception("Expiry failure");
var generation = session.Generation; session.Clear();
if (session.Token != null || session.IsAvailable(1000) || session.Generation <= generation) throw new Exception("Clear failure");
Reject(() => session.Accept(token, "admin", id, 5000, 1000));
Reject(() => session.Accept(token, "learner", id, double.NaN, 1000));
Reject(() => session.Accept("secret", "learner", id, 5000, 1000));
Reject(() => session.Accept(token, "learner", id, 999, 1000));
Console.WriteLine("PASS: native URL policy, credential validation, expiry and generation invalidation (actual pure C#, no Unity/network hardware).");
var input = new PairingInput();
foreach (var c in "trail.example") input.Append(c);
input.Append('@'); if (input.Origin != "https://trail.example") throw new Exception("Unexpected input character");
input.EditingCode = true; foreach (var c in "12345678extra9") input.Append(c);
if (input.Code != "12345678") throw new Exception("Unbounded code");
if (input.TakeCode(false) != "12345678" || input.Code != "") throw new Exception("Code not cleared on submit");
Reject(() => input.TakeCode(false)); Reject(() => input.SelectUsb(false));
input.SelectUsb(true); foreach (var c in "87654321") input.Append(c);
Reject(() => input.TakeCode(false));
if (input.TakeCode(true) != "87654321") throw new Exception("USB selection failure");
input.SelectHttps(); for (var i = 0; i < 200; i++) input.Append('a');
if (input.Origin.Length != 128 || input.UsbLoopback) throw new Exception("Endpoint cap or transport reset failure");
Console.WriteLine("PASS: headset pairing input limits, allowed characters, role-code clearing and development-only USB selection.");
