"""Generate explicit AOT-safe DTO readers/writers and shape data from Zod's JSON Schema.
Run export-schemas.ts first. Refinements belong in ContractValidation.cs and shared corpus.
No runtime reflection, source generation, external serializer, or Unity dependency.
"""
import json, sys
from pathlib import Path
schemas = json.load(open(sys.argv[1]))['schemas']
root = Path('apps/quest/Assets/Trail/Contracts')
# Give stable public names to inline domain objects.
aliases = {'WorkspaceDefinition.calibrationMarksM':'CalibrationMarks', 'MotionFrame.hands':'HandSamples', 'Recording.markers.item':'StepMarker', 'Recording.audio':'AudioAsset', 'RecordingMetadata.markers.item':'StepMarker', 'RecordingMetadata.audio':'AudioAsset', 'GuideSnapshot.nextGateByHand':'NextGateByHand', 'GuideSnapshot.tracking':'HandTracking'}
models = {}
def nullable(s):
    if 'anyOf' in s and len(s['anyOf']) == 2 and any(x.get('type') == 'null' for x in s['anyOf']):
        return next(x for x in s['anyOf'] if x.get('type') != 'null')
    return None
def pascal(s): return s[0].upper()+s[1:]
def shape(s):
    if '$ref' in s: return schemas[s['$ref']]
    return s
def typ(s, path):
    n=nullable(s)
    if n is not None:
        t=typ(n,path); return t+'?' if t in ['int','long','double','bool','CanonicalPose','Vector3','Quaternion'] else t
    if '$ref' in s:
        name=s['$ref']
        if name in ['Pose','Vec3','Quat']: return {'Pose':'CanonicalPose','Vec3':'Vector3','Quat':'Quaternion'}[name]
        r=schemas[name]
        if r.get('type')=='object' or 'oneOf' in r: register(name,r); return name
        return typ(r,path)
    t=s.get('type')
    if t=='string': return 'string'
    if t=='boolean': return 'bool'
    if t in ['number','integer']:
        if t=='integer': return 'int' if s.get('maximum',1e30)<=2147483647 else 'long'
        return 'int' if isinstance(s.get('const'),int) else 'double'
    if t=='array': return typ(s.get('items') if isinstance(s.get('items'),dict) else s['prefixItems'][0],path+'.item')+'[]'
    if t=='object':
        if 'propertyNames' in s: return 'Dictionary<string, CanonicalPose>'
        name=aliases.get(path, ''.join(pascal(x) for x in path.split('.')))
        register(name,s); return name
    raise ValueError((s,path))
def register(name,s):
    if name in models: return
    models[name]=s
    for k,v in props(s).items(): typ(v,name+'.'+k)
def props(s):
    if 'oneOf' in s:
        out={}
        for opt in s['oneOf']: out.update(opt['properties'])
        return out
    return s['properties']
for name,s in list(schemas.items()):
    if name!='Pose' and (s.get('type')=='object' or 'oneOf' in s): register(name,s)
# For optional numeric properties, retain omission distinctly from zero.
def fieldtype(s,k,v,name):
    t=typ(v,name+'.'+k)
    if 'oneOf' not in s and k not in s.get('required',[]) and t in ['int','long','double','bool']: t+='?'
    return t
header='// Generated by packages/contracts/tools/generate-csharp.py; regenerate from Zod schemas.\nusing System;\nusing System.Collections.Generic;\nusing System.Linq;\nusing System.Numerics;\n\nnamespace Trail.Contracts\n{\n'
classes=[header]
for name,s in models.items():
    classes.append('    public sealed class '+name+'\n    {\n')
    for k,v in props(s).items(): classes.append(f'        public {fieldtype(s,k,v,name)} {pascal(k)} {{ get; set; }}\n')
    classes.append('    }\n')
classes.append('}\n'); (root/'ContractModels.cs').write_text(''.join(classes))
def read(s,e,path):
    n=nullable(s)
    if n is not None: return f'({e} == null ? ({typ(s,path)})null : {read(n,e,path)})'
    if '$ref' in s:
        name=s['$ref']; r=schemas[name]
        if name in ['Pose','Vec3','Quat'] or r.get('type')=='object' or 'oneOf' in r: return f'Read{name}({e})'
        return read(r,e,path)
    t=s['type']
    if t in ['number','integer']: return f'({typ(s,path)})(double){e}'
    if t=='string': return f'(string){e}'
    if t=='boolean': return f'(bool){e}'
    if t=='array':
        it=s.get('items') if isinstance(s.get('items'),dict) else s['prefixItems'][0]
        return f'((List<object>){e}).Select(item => {read(it,"item",path+".item")}).ToArray()'
    if t=='object':
        if 'propertyNames' in s: return f'((Dictionary<string, object>){e}).ToDictionary(pair => pair.Key, pair => ReadPose(pair.Value), StringComparer.Ordinal)'
        return f'Read{typ(s,path)}({e})'
    raise ValueError(s)
def write(s,e,path):
    n=nullable(s)
    if n is not None:
        underlying=typ(n,path)
        return f'({e} == null ? null : {write(n,e+(".Value" if underlying in ["int","long","double","bool","CanonicalPose","Vector3","Quaternion"] else ""),path)})'
    if '$ref' in s:
        name=s['$ref']; r=schemas[name]
        if name in ['Pose','Vec3','Quat'] or r.get('type')=='object' or 'oneOf' in r: return f'Write{name}({e})'
        return write(r,e,path)
    t=s['type']
    if t in ['number','integer','string','boolean']: return f'(object){e}'
    if t=='array':
        it=s.get('items') if isinstance(s.get('items'),dict) else s['prefixItems'][0]
        return f'({e} == null ? null : {e}.Select(item => {write(it,"item",path+".item")}).ToList())'
    if t=='object':
        if 'propertyNames' in s: return f'({e} == null ? null : {e}.ToDictionary(pair => pair.Key, pair => WritePose(pair.Value), StringComparer.Ordinal))'
        return f'Write{typ(s,path)}({e})'
    raise ValueError(s)
cs=[header, '    public static partial class ContractJson\n    {\n']
semantic={'Recording','RecordingMetadata','AudioAsset','TutorialStep','Tutorial','TutorialProvenance','TutorialDraftStep','TutorialDraftEdit','GuideSnapshot','SceneReferenceManifest','CoachAssessment','InspectionRequest','InspectionResult'}
for name,s in models.items():
    if name in schemas:
        cs.append(f'        public static {name} Parse{name}(string json) {{ var raw = StrictJson.Parse(json); ContractShape.Validate("{name}", raw); return Read{name}(raw); }}\n')
        cs.append(f'        public static string Serialize{name}({name} value) {{ var json = StrictJson.Stringify(Write{name}(value)); Parse{name}(json); return json; }}\n')
    cs.append(f'        private static {name} Read{name}(object value)\n        {{\n            var map = (Dictionary<string, object>)value;\n            var result = new {name}();\n')
    for k,v in props(s).items():
        expr=read(v,f'map["{k}"]',name+'.'+k)
        cs.append(f'            if (map.ContainsKey("{k}")) result.{pascal(k)} = {expr};\n')
    if name in semantic: cs.append('            ContractValidation.Validate(result);\n')
    cs.append('            return result;\n        }\n')
    cs.append(f'        private static object Write{name}({name} value)\n        {{\n            if (value == null) return null;\n            var map = new Dictionary<string, object>(StringComparer.Ordinal);\n')
    variants=s.get('oneOf',[s])
    for opt in variants:
        if 'oneOf' in s:
            disc='status' if name=='HandSample' else 'type'; literal=opt['properties'][disc]['const']
            cs.append(f'            if (value.{pascal(disc)} == "{literal}")\n            {{\n')
        for k,v in opt['properties'].items():
            e='value.'+pascal(k)
            optional=k not in opt.get('required',[])
            if optional:
                cs.append(f'            if ({e} != null) map["{k}"] = {write(v,e+".Value",name+"."+k)};\n')
            else: cs.append(f'            map["{k}"] = {write(v,e,name+"."+k)};\n')
        if 'oneOf' in s: cs.append('                return map;\n            }\n')
    if 'oneOf' in s: cs.append('            throw new ContractException("Unknown union discriminator");\n')
    else: cs.append('            return map;\n')
    cs.append('        }\n')
cs.append('    }\n}\n'); (root/'ContractJson.Generated.cs').write_text(''.join(cs))
data=[header,'    internal static class ContractShapeData\n    {\n        internal static readonly Dictionary<string, object> Schemas = new Dictionary<string, object>\n        {\n']
for name,s in schemas.items():
    raw=json.dumps(s,separators=(',',':')); data.append(f'            {{ "{name}", StrictJson.Parse(@"{raw.replace(chr(34),chr(34)*2)}") }},\n')
data.append('        };\n    }\n}\n'); (root/'ContractShapeData.Generated.cs').write_text(''.join(data))
